"
"
"latex
"
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
filetype plugin on
"
"
" histprico longo de comando
set history=1000
"
" conf tab completação
set wildmode=list:longest
"
" cursor tropicante
set scrolloff=3
"
" identação ON
filetype indent on
set autoindent
set smartindent
"
" reunindo swaps&tmp
set backupdir=~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp
"
"
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
set spelllang=pt
map <F6> :setlocal spell <CR>
map <F7> :setlocal nospell <CR>
"
set nocompatible
"
set tabstop=4        " tab width is 4 spaces
set shiftwidth=4     " indent also with 4 spaces
set expandtab        " expand tabs to spaces
retab
"
"
set showtabline=2
"
set t_Co=256
syntax on
"
" turn line numbers on
set number
"
" busca incremental.
set incsearch
" salva ao alternar buffers
set aw
" troca rápida entre janelas
set ttyfast
